spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/dev?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    username: root
    password: root
    dbType: mysql

logging:
  level:
    root: debug
    
server:
  context-path: /agile-bpm-platform
  

ab:
  security:
    auth-ingores: /login.*,/swagger-*,/v2/api-docs*